# Generated by Django 5.2.6 on 2025-09-20 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image_subcategory_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterprompt',
            name='reference_name',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='masterprompt',
            name='reference_photo',
            field=models.ImageField(blank=True, null=True, upload_to='reference_photos/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory_images/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='ViewOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='view_images/')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.subcategory')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('subcategory', 'name')},
            },
        ),
        migrations.AddField(
            model_name='masterprompt',
            name='view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.viewoption'),
        ),
    ]
