# Generated by Django 5.2.6 on 2025-09-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='viewoption',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='viewoption',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='viewoption',
            name='negative_prompt',
        ),
        migrations.RemoveField(
            model_name='viewoption',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='viewoption',
            name='strength',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subcategory/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='viewoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='viewoption/'),
        ),
        migrations.AddField(
            model_name='viewoption',
            name='prompt_override',
            field=models.TextField(blank=True, help_text='(Opcional) Prompt secreto para esta vista.', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='viewoption',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='GeneratedImage',
        ),
    ]
